{-# LANGUAGE CPP #-}
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Control.Monad
-- import TestUtils
import qualified Turtle as Tu
import qualified Control.Foldl as Fold
import System.Directory
import System.FilePath
import System.Process (readProcess)
import TestUtils

import Test.Hspec.Runner
import qualified Spec

-- ---------------------------------------------------------------------

data BuildType = BuildV1 | BuildV2 | BuildStack deriving (Eq,Show)

main :: IO ()
main = do
  let build = BuildV1
  prefix <- testDataDir
  copyTestDirs prefix
  cleanupDirs prefix (Tu.ends "/.stack-work")
  cleanupDirs prefix (Tu.ends "/dist")
  cleanupDirs prefix (Tu.ends "/dist-newstyle")
  deleteStackFiles prefix
  -- if True
  case build of
    BuildStack -> setupStackFiles prefix
    _ -> setupDistDirs build prefix
  hspec Spec.spec

-- ---------------------------------------------------------------------

setupStackFiles :: FilePath -> IO ()
setupStackFiles prefix =
  forM_ (stackFiles prefix) $ \f ->
    writeFile f stackFileContents

setupDistDirs :: BuildType -> FilePath -> IO ()
setupDistDirs build prefix =
  forM_ (cabalDirs prefix) $ \d -> do
    withCurrentDirectory d $ do
      case build of
        BuildV1 -> do
          run "cabal" [ "v1-install", "--dependencies-only" ]
          run "cabal" [ "v1-configure" ]
        BuildV2 -> do
          -- run "cabal" [ "new-configure" ]
          run "cabal" [ "new-build" ]
        BuildStack -> error "setupDistDirs"

-- This is shamelessly copied from cabal-helper GhcSession test.
run :: String -> [String] -> IO ()
run x xs = do
  print $ x:xs
  o <- readProcess x xs ""
  putStrLn o
  return ()

-- ---------------------------------------------------------------------

cabalDirs :: FilePath -> [FilePath]
cabalDirs prefix = map (\p -> prefix </> p)
  [  "./test/testdata/"
   , "./test/testdata/cabal/cabal3/"
   , "./test/testdata/cabal/foo/"
   , "./test/testdata/cabal/cabal4/"
   , "./test/testdata/cabal/cabal1/"
   , "./test/testdata/cabal/cabal2/"
  ]

stackFiles :: FilePath -> [FilePath]
stackFiles prefix = map (++"stack.yaml") (cabalDirs prefix)

-- |Choose a resolver based on the current compiler, otherwise HaRe/ghc-mod will
-- not be able to load the files
resolver :: String
resolver =
#if (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,6,3,0)))
  "resolver: nightly-2018-12-18"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,6,2,0)))
  "resolver: nightly-2018-12-17"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,6,0,0)))
  "resolver: nightly-2018-11-11"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,4,4,0)))
  "resolver: lts-12.17"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,4,3,0)))
  "resolver: nightly-2018-06-29"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,4,2,0)))
  "resolver: nightly-2018-04-24"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,4,1,0)))
  "resolver: nightly-2018-04-21" -- last one for GHC 8.4.1
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,2,2,0)))
  "resolver: lts-11.6"
#elif __GLASGOW_HASKELL__ >= 802
  "resolver: nightly-2017-09-02"
#elif __GLASGOW_HASKELL__ > 710
  "resolver: nightly-2017-05-23"
#else
  "resolver: lts-6.13"
#endif

-- ---------------------------------------------------------------------

stackFileContents :: String
stackFileContents = unlines
  [ "# WARNING: THIS FILE IS AUTOGENERATED IN test/Main.hs. IT WILL BE OVERWRITTEN ON EVERY TEST RUN"
  , resolver
  , "packages:"
  , "- '.'"
  , "extra-deps: "
  -- , "- conversion-1.2.1"
  -- , "- conversion-bytestring-1.0.1"
  -- , "- conversion-case-insensitive-1.0.0.0"
  -- , "- conversion-text-1.0.1"
  -- , "- syb-0.7"
#if (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,4,2,0)))
    , "- conversion-1.2.1"
    , "- conversion-case-insensitive-1.0.0.0"
    , "- conversion-text-1.0.1"
    , "- conversion-bytestring-1.0.1"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,4,1,0)))
  -- , "- Cabal-2.2.0.0"
  -- , "- attoparsec-0.13.2.2"
  -- , "- base-prelude-1.2.0.1"
  -- , "- case-insensitive-1.2.0.10"
  -- , "- hashable-1.2.7.0"
  -- , "- scientific-0.3.5.2"
  -- , "- integer-logarithms-1.0.2.1"
  -- , "- primitive-0.6.3.0"
#elif (defined(MIN_VERSION_GLASGOW_HASKELL) && (MIN_VERSION_GLASGOW_HASKELL(8,2,2,0)))
    , "- conversion-1.2.1"
    , "- conversion-bytestring-1.0.1"
    , "- conversion-case-insensitive-1.0.0.0"
    , "- conversion-text-1.0.1"
    , "- syb-0.7"
#elif __GLASGOW_HASKELL__ >= 802
    , "- conversion-1.2.1"
    , "- conversion-bytestring-1.0.1"
    , "- conversion-case-insensitive-1.0.0.0"
    , "- conversion-text-1.0.1"
    , "- syb-0.7"
#elif __GLASGOW_HASKELL__ > 710
#endif
  ]

-- ---------------------------------------------------------------------

copyTestDirs :: FilePath -> IO ()
copyTestDirs prefix = do
  copyTree "./test/testdata" (prefix </> "test" </> "testdata")

-- ---------------------------------------------------------------------

cleanupDirs :: FilePath -> Tu.Pattern t -> IO ()
cleanupDirs prefix ending = do
  dirs <- getDirs prefix ending
  forM_ dirs  $ \dir -> Tu.rmtree dir

deleteStackFiles :: FilePath -> IO ()
deleteStackFiles prefix = forM_ (stackFiles prefix) $ \f -> do
  exists <- doesFileExist f
  when exists $ removeFile f

getDirs :: FilePath -> Tu.Pattern t -> IO [Tu.FilePath]
getDirs prefix ending = do
  let
    dirs = Tu.find ending (Tu.decodeString prefix Tu.</> "./test")
  Tu.fold dirs Fold.list

listStackDirs :: Tu.FilePath -> IO ()
listStackDirs prefix = Tu.sh $ do
  dirs <- Tu.find (Tu.ends "/.stack-work") (prefix Tu.</> "/test")
  mapM Tu.echo $ Tu.textToLines $ "found:" Tu.<> (Tu.repr dirs)
