defaults: &defaults
  working_directory: ~/build
  docker:
    - image: alanz/haskell-hie-ci
  steps:
    - checkout
    - run:
        command: git submodule sync --recursive
    - run:
        command: git submodule update --recursive --init
    - run:
        name: Write provided stack.yaml with predictable name
        command: cp ${STACK_FILE} stack-build.txt

    - run:
        name: Figure out resolver for better caching
        command: grep '^resolver:' stack-build.txt > resolver.txt

    - run:
        name: Create a composite cabal file for changes detection
        command: find . -name "*.cabal" | grep -v "stack-work" | xargs cat > all-cabal.txt

    - restore_cache:
        keys:
          - stack-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}-{{ checksum "all-cabal.txt" }}
          - stack-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}
          - stack-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "resolver.txt" }}

    - run:
        name: Stack setup
        command: stack -j 2 --stack-yaml=${STACK_FILE} setup

        name: Install happy
        command: stack -j 2 --stack-yaml=${STACK_FILE} install happy

        name: Install alex
        command: stack -j 2 --stack-yaml=${STACK_FILE} install alex

        name: Install cabal-install
        command: stack -j 2 --stack-yaml=${STACK_FILE} install cabal-install

    - save_cache:
        key: stack-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "resolver.txt" }}
        paths:
          - ~/.local/bin
          - ~/.stack
          - ~/.cache
          - ~/build/HaRe/.stack-work

    - restore_cache:
          key: stack-work-dirs-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}

    - run:
        name: Compile + Test
        command: stack -j 2 --stack-yaml=${STACK_FILE} test --dump-logs
        no_output_timeout: 120m

    - save_cache:
        key: stack-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}
        paths:
          - ~/.local/bin
          - ~/.stack
          - ~/.cache
          - ~/build/HaRe/.stack-work

    - save_cache:
        key: stack-cache-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}-{{ checksum "all-cabal.txt" }}
        paths:
          - ~/.local/bin
          - ~/.stack
          - ~/.cache
          - ~/build/HaRe/.stack-work

    - save_cache:
        key: stack-work-dirs-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}
        paths:
          - ~/build/.stack-work
          - ~/build/hie-plugin-api/.stack-work
          - ~/build/HaRe/.stack-work

version: 2
jobs:
  ghc-8.4.2:
    environment:
      - STACK_FILE: "stack-8.4.2.yaml"
    <<: *defaults

  ghc-8.4.3:
    environment:
      - STACK_FILE: "stack-8.4.3.yaml"
    <<: *defaults

  ghc-8.4.4:
    environment:
      - STACK_FILE: "stack-8.4.4.yaml"
    <<: *defaults

  ghc-8.6.1:
    environment:
      - STACK_FILE: "stack-8.6.1.yaml"
    <<: *defaults

  ghc-8.6.3:
    environment:
      - STACK_FILE: "stack-8.6.3.yaml"
    <<: *defaults

  ghc-8.6.4:
    environment:
      - STACK_FILE: "stack-8.6.4.yaml"
    <<: *defaults

  ghc-8.6.5:
    environment:
      - STACK_FILE: "stack-8.6.5.yaml"
    <<: *defaults
  cabal:
    working_directory: ~/build
    docker:
      - image: quay.io/haskell_works/ghc-8.6.5
    steps:
      - checkout
      - run:
          name: Sync submodules
          command: git submodule sync --recursive
      - run:
          name: Update submodules
          command: git submodule update --recursive --init
      - restore-cache:
          keys:
            - cabal-{{ .Environment.HIE_CACHE }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: Cabal version
          command: cabal --version
      - run:
          name: Update
          command: cabal new-update
      - run:
          name: Configure
          command: cabal new-configure --enable-tests
      - run:
          name: Build
          command: cabal new-build -j1 # need j1, else ghc-lib-parser triggers OOM
          no_output_timeout: 30m
      - save_cache:
          key: cabal-{{ .Environment.HIE_CACHE }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}
          paths:
            - ~/.cabal

workflows:
  version: 2
  multiple-ghcs:
    jobs:
      - ghc-8.4.2
      - ghc-8.4.3
      - ghc-8.4.4
      - ghc-8.6.1
      - ghc-8.6.3
      - ghc-8.6.4
      - ghc-8.6.5
      - cabal
